IF DB_ID(N'EnterpriseDataPlatform') IS NULL
BEGIN
    CREATE DATABASE EnterpriseDataPlatform;
END
GO

ALTER DATABASE EnterpriseDataPlatform SET RECOVERY FULL;
GO

ALTER DATABASE EnterpriseDataPlatform SET READ_COMMITTED_SNAPSHOT ON;
GO
